# Generated by Django 4.2.4 on 2023-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
